### ISSUE TITLE
Recursive functions for both spaces() and markup_space()

### ISSUE THREAD

**Issue by psolin** [psolin/pymkup#15]
I know there is a way to convert this code to always search for the next item in the child keys. I just haven't figured it out yet.

**Comment by supersonic1999** [comment]
Hi, id like to look into this. Any chance you have a sample PDF that i can use to input?

**Comment by psolin** [comment]
I'll add some tests over the next few days that can be pulled. I just have to re-install Revu on my computer.

**Comment by supersonic1999** [comment]
Cheers

**Comment by psolin** [comment]
This is sort of broken, but I want to put it here for reference. I was getting close.

`def markup_space(self, markup):
        markup_spaces = {}
        spaces_list = []
        if markup.P.BSISpaces:
            def walk(node):
                titles = []
                titles.append(markup.P.BSISpaces[0].Title[1:-1])
                for key, item in node.items():
                    if key == '/Title':
                        titles.append(item[1:-1])
                    elif key == '/Kids':
                        titles.append(item[0].Title[1:-1])
                        walk(item[0].Kids[0])
                return(titles)
        return(walk(markup.P.BSISpaces[0]))`

**Comment by supersonic1999** [comment]
Looks cool! Pretty sure ive done it recursively tbh, just need a test file

**Comment by psolin** [comment]
OK, I've uploaded a few to the tests directory. Check markup-deep-spaces.pdf. In the markups, you'll need to get to this (one per markup):

Level 3-Area B-Room 305-Sub Room 2
Level 3-Area B-Room 304
Level 3-Area B
Level 3-Area B-Hallway 330
Level 3-Area B-Room 106
Level 3-Area B-Room 302
Level 3-Area B-Room 302-Sub Room
Level 3-Area B-Room 303
Level 4-Area A-Room 401
Level 4-Area A
Level 4-Area A-Hallway 2

This is what the spaces tree looks like:
<img width="190" alt="Screen Shot 2021-04-20 at 8 40 05 PM" src="https://user-images.githubusercontent.com/6238847/115488968-9fde6880-a218-11eb-85b9-9bcf48bfa0dd.png">

**Comment by supersonic1999** [comment]
Ive managed to code the spaces() function recursively now! but the incorrect space output with markup_space() is eluding me currently. 

It seems to be either `space = self.markup_space(markup)` inside markups() is passing in the wrong variable or `markup.P.BSISpaces[0].Kids[0]` inside markup_space isnt the right way to do it...

**Comment by psolin** [comment]
This has been merged.
